### ISSUE TITLE
COPY FROM DATABASE cause Segmentation fault

### ISSUE THREAD

**Issue by AAG81** [duckdb/duckdb-mysql#103]
Copying a MySQL database to a local DuckDB database using 
COPY FROM DATABASE results in a segmentation fault.
```
duckdb --version : v1.1.3 19864453f7
mysql: Server version: 8.0.35-commercial MySQL Enterprise Server - Commercial
OS: Debian GNU/Linux 12 (bookworm)
```
**Steps to reproduce:**
```
duckdb my_duckdb
ATTACH 'host=127.0.0.1 user=myuser password=mystrongpass port=3306 database=mydb' AS mydb (TYPE MYSQL);
use mydb;
COPY FROM DATABASE mydb TO my_duckdb; 
Segmentation fault
```

**Comment by Mytherin** [comment]
Thanks for the report!

This might already be fixed in the nightly - could you try installing the nightly to check if the problem persists?

```sql
force install mysql from core_nightly;
```

**Comment by AAG81** [comment]
Thank you,
I tested it with a 20GB database, and my system froze. However, it worked successfully with a smaller database using core_nightly. I'll close this issue as resolved.
